### ISSUE TITLE
Error when total = NA and format contains :bar

### ISSUE THREAD

**Issue by Fuco1** [r-lib/progress#111] opened 2020-10-19 21:18 UTC
These lines 

https://github.com/r-lib/progress/blob/b146a6a74d14c1cf4a3689ae745a0c0f38a355d2/R/progress.R#L422-L423

cause 

    Error in rep("", complete_len) : invalid 'times' argument

because the ratio is `NA`.

**Comment by gaborcsardi** [comment] 2023-11-01 14:46
Duplicate of #119.

**Closed by gaborcsardi** 2023-11-01 14:46 UTC
